name: cards_net_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2 
  local_auth: ^2.1.6 
  flutter_colorpicker: ^1.1.0 
  shared_preferences: ^2.2.2    
  firebase_core: ^2.32.0 
  cloud_firestore: ^4.15.8 
  firebase_auth: ^4.15.3  # 👈 تمت إضافتها لتفعيل ميزة "تغيير كلمة المرور" في الإعدادات
  pdf: ^3.11.0          
  printing: ^5.12.0     
  intl: ^0.19.0          
  marquee: ^2.2.3        
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  excel: ^4.0.3
  google_fonts: ^6.1.0  
  audioplayers: ^5.2.1  
  url_launcher: ^6.2.5
  http: ^1.2.0  # 👈 للاتصال بسيرفر Render
  share_plus: ^7.2.2  # 👈 لتفعيل ميزة "مشاركة الكروت والسندات"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # 👇 تعريف مجلد الأصوات للتطبيق
  assets:
    - assets/sounds/
