name: cards_net_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2 
  local_auth: ^2.1.6 
  flutter_colorpicker: ^1.1.0 
  shared_preferences: ^2.2.2    
  firebase_core: ^3.6.0 
  cloud_firestore: ^5.4.4 
  firebase_auth: ^5.3.1  
  pdf: ^3.11.0          
  printing: ^5.12.0     
  intl: ^0.20.2          # تم التحديث ليتوافق مع flutter_localizations
  marquee: ^2.2.3        
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  excel: ^4.0.3
  google_fonts: ^6.1.0  
  audioplayers: ^6.0.0  
  url_launcher: ^6.2.5
  http: ^1.2.0 
  share_plus: ^13.1.0
  flutter_localizations: # لدعم الترجمة
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
