name: cards_net_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  # قمنا بتحديد النسخة بدقة لتفعيل المميزات الحديثة
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2 # مكتبة العقل (Provider)
  local_auth: ^2.1.6 # مكتبة البصمة 
  flutter_colorpicker: ^1.1.0 # مكتبة عجلة الألوان الشاملة
  firebase_core: ^2.32.0 # 👈 الإضافة الجديدة: مكتبة الاتصال بخوادم فايربيس
  cloud_firestore: ^4.15.8 # 👈 مكتبة قاعدة البيانات السحابية

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
