name: Build APK and Deploy Web

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: جلب الكود من المستودع
        uses: actions/checkout@v3

      - name: تجهيز بيئة فلاتر
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 👈 خطوة إجبارية لبناء مجلد أندرويد رسمي وجديد كلياً يتوافق مع مكاتبك
      - name: إعادة إنشاء مجلد الأندرويد والويب بنقاء
        run: |
          rm -rf android
          rm -rf web
          flutter create . --platforms android,web

      # 👈 خطوة تصحيح استدعاء المكتبة البديلة وحفظ البايتات بالشكل الصحيح
      - name: تحديث استدعاءات المكتبة في الكود البرمجي
        run: |
          sed -i "s/import 'package:image_gallery_saver\/image_gallery_saver.dart';/import 'package:gal\/gal.dart';/g" lib/features/user_panel/screens/network_store_screen.dart
          sed -i "s/import 'package:image_gallery_saver\/image_gallery_saver.dart';/import 'package:gal\/gal.dart';/g" lib/features/user_panel/screens/my_cards_screen.dart
          sed -i "s/ImageGallerySaver.saveImage/Gal.putImageBytes/g" lib/features/user_panel/screens/network_store_screen.dart
          sed -i "s/ImageGallerySaver.saveImage/Gal.putImageBytes/g" lib/features/user_panel/screens/my_cards_screen.dart

      - name: تنظيف وتحميل المكاتب
        run: |
          flutter clean
          flutter pub get

      - name: بناء نسخة الويب
        run: flutter build web --release

      - name: النشر على سيرفرات فايربيس هوسيتنج
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: 'netcardsapp'

      - name: بناء تطبيق الأندرويد APK
        run: flutter build apk --release

      - name: حفظ ملف APK لتنزيله
        uses: actions/upload-artifact@v4
        with:
          name: NetCardsApp-Android
          path: build/app/outputs/flutter-apk/app-release.apk
