name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: جلب الكود من المستودع
        uses: actions/checkout@v3

      - name: تجهيز بيئة فلاتر
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'

      - name: تنظيف بيئة العمل
        run: flutter clean

      - name: تحميل المكاتب والإضافات
        run: flutter pub get

      - name: تفعيل دعم الويب
        run: flutter create . --platforms web

      - name: بناء نسخة الويب
        run: flutter build web --base-href "/cards-net-app/" --no-wasm-dry-run

      - name: النشر على رابط جيت هاب
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
